# Generated by Django 3.1 on 2020-09-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200904_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
